"""Versioned curated research catalog. Reference intervals come from source labs, not this catalog."""

MODEL_VERSION = "interpretable-0.2.0"
ONTOLOGY_VERSION = "hallmarks-2023-v1"
EVIDENCE_VERSION = "curated-2026-09-v1"
# concept: label, canonical unit, domain membership, favorable direction, plausibility bounds, aliases
CONCEPTS = {
    "APOB": (
        "ApoB",
        "mg/dL",
        ["metabolic", "cardiovascular"],
        -1,
        [1, 500],
        ["apo b", "apolipoprotein b"],
    ),
    "TRIGLYCERIDES": (
        "Triglycerides",
        "mg/dL",
        ["metabolic"],
        -1,
        [1, 5000],
        ["triglyceride", "tg"],
    ),
    "GLUCOSE": (
        "Fasting glucose",
        "mg/dL",
        ["metabolic"],
        -1,
        [10, 1000],
        ["glucose", "fasting glucose"],
    ),
    "HBA1C": (
        "HbA1c",
        "%",
        ["metabolic"],
        -1,
        [2, 25],
        ["a1c", "hba1c", "hemoglobin a1c"],
    ),
    "INSULIN": (
        "Fasting insulin",
        "uIU/mL",
        ["metabolic"],
        -1,
        [0.1, 1000],
        ["insulin", "fasting insulin"],
    ),
    "HDL": (
        "HDL cholesterol",
        "mg/dL",
        ["metabolic"],
        1,
        [1, 250],
        ["hdl-c", "hdl cholesterol"],
    ),
    "LDL": (
        "LDL cholesterol",
        "mg/dL",
        ["cardiovascular"],
        -1,
        [1, 1000],
        ["ldl-c", "ldl cholesterol"],
    ),
    "TOTAL_CHOLESTEROL": ("Total cholesterol", "mg/dL", ["metabolic", "cardiovascular"], -1, [20, 1500], ["total cholesterol", "cholesterol total"]),
    "VLDL": ("VLDL cholesterol", "mg/dL", ["metabolic"], -1, [0, 500], ["vldl", "vldl cholesterol", "cholesterol vldl"]),
    "NON_HDL": ("Non-HDL cholesterol", "mg/dL", ["metabolic", "cardiovascular"], -1, [1, 1500], ["non hdl cholesterol", "non-hdl cholesterol"]),
    "TC_HDL_RATIO": ("Total cholesterol / HDL ratio", "ratio", ["metabolic", "cardiovascular"], -1, [0.1, 30], ["cholesterol hdl cholesterol", "total cholesterol hdl ratio"]),
    "LDL_HDL_RATIO": ("LDL / HDL ratio", "ratio", ["metabolic", "cardiovascular"], -1, [0.1, 30], ["ldl hdl cholesterol", "ldl hdl ratio"]),
    "LPA": ("Lipoprotein(a)", "mg/dL", ["cardiovascular"], -1, [0.01, 1000], ["lipoprotein(a)", "lp(a)", "lpa"]),
    "APOA1": ("Apolipoprotein A1", "mg/dL", ["cardiovascular"], 0, [1, 500], ["apolipoprotein a1", "apo a1"]),
    "APOB_APOA1_RATIO": ("ApoB / ApoA1 ratio", "ratio", ["cardiovascular"], -1, [0.01, 20], ["apolipoprotein b/a1 ratio", "apob apoa1 ratio"]),
    "HSCRP": (
        "hs-CRP",
        "mg/L",
        ["inflammatory"],
        -1,
        [0.01, 500],
        ["hs-crp", "high sensitivity crp"],
    ),
    "CRP": ("C-reactive protein", "mg/L", ["inflammatory"], -1, [0.01, 500], ["c-reactive protein", "c reactive protein quantitative", "crp quantitative"]),
    "ESR": ("Erythrocyte sedimentation rate", "mm/hr", ["inflammatory", "hematology"], -1, [0, 200], ["erythrocyte sedimentation rate", "esr"]),
    "SBP": (
        "Systolic blood pressure",
        "mmHg",
        ["cardiovascular"],
        -1,
        [40, 300],
        ["systolic", "systolic blood pressure"],
    ),
    "DBP": (
        "Diastolic blood pressure",
        "mmHg",
        ["cardiovascular"],
        -1,
        [20, 200],
        ["diastolic"],
    ),
    "RHR": (
        "Resting heart rate",
        "bpm",
        ["cardiovascular", "recovery"],
        -1,
        [20, 220],
        ["resting heart rate", "average_heart_rate"],
    ),
    "HRV": (
        "Heart rate variability",
        "ms",
        ["recovery"],
        1,
        [1, 400],
        ["hrv", "average_hrv"],
    ),
    "SLEEP": (
        "Sleep duration",
        "h",
        ["recovery"],
        1,
        [0.1, 24],
        ["sleep", "sleep duration", "total_sleep_duration"],
    ),
    "STEPS": ("Daily steps", "steps", ["functional"], 1, [0, 100000], ["steps"]),
    "VO2MAX": (
        "VO₂ max",
        "mL/kg/min",
        ["functional", "cardiovascular"],
        1,
        [5, 100],
        ["vo2max", "vo2 max"],
    ),
    "GRIP": (
        "Grip strength",
        "kg",
        ["musculoskeletal"],
        1,
        [1, 150],
        ["grip strength", "hand grip"],
    ),
    "GAIT": ("Gait speed", "m/s", ["functional"], 1, [0.05, 4], ["gait speed"]),
    "WAIST": (
        "Waist circumference",
        "cm",
        ["body"],
        -1,
        [20, 250],
        ["waist", "waist circumference"],
    ),
    "MUSCLE": (
        "Lean mass",
        "kg",
        ["musculoskeletal"],
        1,
        [5, 150],
        ["lean mass", "muscle mass"],
    ),
    "WEIGHT": ("Body weight", "kg", ["body"], 0, [20, 400], ["weight", "body weight"]),
    "ALT": ("ALT", "U/L", ["liver"], -1, [1, 10000], ["alanine aminotransferase"]),
    "AST": ("AST", "U/L", ["liver"], -1, [1, 10000], ["aspartate aminotransferase"]),
    "GGT": ("GGT", "U/L", ["liver"], -1, [1, 10000], ["gamma gt"]),
    "CREATININE": ("Creatinine", "mg/dL", ["kidney"], 0, [0.1, 30], ["creatinine"]),
    "EGFR": ("eGFR", "mL/min/1.73m2", ["kidney"], 1, [1, 200], ["egfr"]),
    "HEMOGLOBIN": (
        "Hemoglobin",
        "g/dL",
        ["hematology"],
        0,
        [1, 25],
        ["hemoglobin", "hgb"],
    ),
    "RBC": ("Red blood cells", "10^6/uL", ["hematology"], 0, [0.1, 20], ["rbc", "red blood cell count"]),
    "HCT": ("Hematocrit", "%", ["hematology"], 0, [1, 80], ["hct", "hematocrit"]),
    "MCV": ("Mean corpuscular volume", "fL", ["hematology"], 0, [20, 200], ["mcv"]),
    "MCH": ("Mean corpuscular hemoglobin", "pg", ["hematology"], 0, [5, 80], ["mch"]),
    "MCHC": ("Mean corpuscular hemoglobin concentration", "g/dL", ["hematology"], 0, [5, 60], ["mchc"]),
    "RDW": ("Red-cell distribution width", "%", ["hematology"], 0, [1, 50], ["rdw", "rdw-cv"]),
    "WBC": ("White blood cells", "10^9/L", ["hematology", "inflammatory", "immune"], 0, [0.1, 200], ["wbc"]),
    "NEUTROPHILS": ("Neutrophils", "%", ["hematology", "immune"], 0, [0, 100], ["neutrophils"]),
    "LYMPHOCYTES": ("Lymphocytes", "%", ["hematology", "immune"], 0, [0, 100], ["lymphocytes"]),
    "MONOCYTES": ("Monocytes", "%", ["hematology", "immune"], 0, [0, 100], ["monocytes"]),
    "EOSINOPHILS": ("Eosinophils", "%", ["hematology", "immune"], -1, [0, 100], ["eosinophils"]),
    "BASOPHILS": ("Basophils", "%", ["hematology", "immune"], 0, [0, 100], ["basophils"]),
    "ANC": ("Absolute neutrophil count", "10^9/L", ["hematology", "immune"], 0, [0, 100], ["absolute neutrophil count", "anc"]),
    "ALC": ("Absolute lymphocyte count", "10^9/L", ["hematology", "immune"], 0, [0, 100], ["absolute lymphocyte count", "alc"]),
    "AMC": ("Absolute monocyte count", "10^9/L", ["hematology", "immune"], 0, [0, 100], ["absolute monocyte count", "amc"]),
    "AEC": ("Absolute eosinophil count", "10^9/L", ["hematology", "immune"], -1, [0, 100], ["absolute eosinophil count", "aec"]),
    "ABC": ("Absolute basophil count", "10^9/L", ["hematology", "immune"], 0, [0, 100], ["absolute basophil count", "abc"]),
    "PLATELETS": ("Platelets", "10^9/L", ["hematology"], 0, [1, 2000], ["platelets"]),
    "MPV": ("Mean platelet volume", "fL", ["hematology"], 0, [1, 40], ["mpv"]),
    "PDW": ("Platelet distribution width", "fL", ["hematology"], 0, [1, 50], ["pdw"]),
    "EAG": ("Estimated average glucose", "mg/dL", ["metabolic"], -1, [10, 1000], ["estimated average glucose", "estimated average glucose eag"]),
    "BILIRUBIN_TOTAL": ("Total bilirubin", "mg/dL", ["liver"], 0, [0.01, 100], ["bilirubin total", "bilirubin-total"]),
    "BILIRUBIN_DIRECT": ("Direct bilirubin", "mg/dL", ["liver"], 0, [0, 100], ["bilirubin direct", "bilirubin-direct"]),
    "BILIRUBIN_INDIRECT": ("Indirect bilirubin", "mg/dL", ["liver"], 0, [0, 100], ["bilirubin indirect", "bilirubin-indirect"]),
    "TOTAL_PROTEIN": ("Total protein", "g/dL", ["liver", "nutrition"], 0, [0.1, 20], ["protein total", "total protein"]),
    "ALBUMIN": ("Albumin", "g/dL", ["liver", "nutrition"], 0, [0.1, 10], ["albumin"]),
    "GLOBULIN": ("Globulin", "g/dL", ["liver", "nutrition"], 0, [0.1, 15], ["globulin"]),
    "AG_RATIO": ("Albumin / globulin ratio", "ratio", ["liver", "nutrition"], 0, [0.01, 20], ["a/g ratio", "albumin globulin ratio"]),
    "AST_ALT_RATIO": ("AST / ALT ratio", "ratio", ["liver"], 0, [0.01, 100], ["sgot/sgpt", "ast alt ratio"]),
    "ALP": ("Alkaline phosphatase", "U/L", ["liver"], 0, [1, 5000], ["alkaline phosphatase", "alp"]),
    "BUN": ("Blood urea nitrogen", "mg/dL", ["kidney"], 0, [0.1, 300], ["blood urea nitrogen", "bun"]),
    "UREA": ("Urea", "mg/dL", ["kidney"], 0, [0.1, 700], ["urea"]),
    "URIC_ACID": ("Uric acid", "mg/dL", ["kidney", "metabolic"], 0, [0.1, 30], ["uric acid"]),
    "SODIUM": ("Sodium", "mmol/L", ["kidney"], 0, [80, 200], ["sodium"]),
    "POTASSIUM": ("Potassium", "mmol/L", ["kidney"], 0, [1, 15], ["potassium"]),
    "CHLORIDE": ("Chloride", "mmol/L", ["kidney"], 0, [50, 200], ["chloride"]),
    "BUN_CREATININE_RATIO": ("BUN / creatinine ratio", "ratio", ["kidney"], 0, [0.1, 200], ["bun/creatinine ratio", "bun creatinine ratio"]),
    "CALCIUM": ("Calcium", "mg/dL", ["nutrition", "musculoskeletal"], 0, [1, 30], ["calcium"]),
    "PHOSPHORUS": ("Phosphorus", "mg/dL", ["nutrition", "musculoskeletal"], 0, [0.1, 30], ["phosphorus", "phosphate"]),
    "IRON": ("Serum iron", "ug/dL", ["nutrition", "hematology"], 0, [1, 1000], ["iron serum", "serum iron"]),
    "TIBC": ("Total iron-binding capacity", "ug/dL", ["nutrition", "hematology"], 0, [1, 1500], ["total iron binding capacity tibc", "tibc"]),
    "UIBC": ("Unsaturated iron-binding capacity", "ug/dL", ["nutrition", "hematology"], 0, [0, 1500], ["unsaturated iron binding capacity", "uibc"]),
    "TRANSFERRIN_SAT": ("Transferrin saturation", "%", ["nutrition", "hematology"], 0, [0, 100], ["transferrin saturation"]),
    "FERRITIN": ("Ferritin", "ng/mL", ["nutrition", "hematology"], 0, [0.1, 10000], ["ferritin"]),
    "LIPASE": ("Lipase", "U/L", ["nutrition"], 0, [0.1, 10000], ["lipase"]),
    "AMYLASE": ("Amylase", "U/L", ["nutrition"], 0, [0.1, 10000], ["amylase"]),
    "MAGNESIUM": ("Magnesium", "mg/dL", ["nutrition", "musculoskeletal"], 0, [0.1, 20], ["magnesium"]),
    "IGE": ("Total immunoglobulin E", "IU/mL", ["immune"], 0, [0, 100000], ["immunoglobulin e ige total", "total ige", "ige"]),
    "RHEUMATOID_FACTOR": ("Rheumatoid factor", "IU/mL", ["immune"], 0, [0, 100000], ["rheumatoid factor quantitative", "rheumatoid factor", "rf"]),
    "T3_TOTAL": ("Total T3", "ng/mL", ["nutrition"], 0, [0.01, 20], ["t3 total", "total t3"]),
    "T4_TOTAL": ("Total T4", "ug/dL", ["nutrition"], 0, [0.1, 100], ["t4 total", "total t4"]),
    "TSH": ("Thyroid-stimulating hormone", "uIU/mL", ["nutrition"], 0, [0.001, 1000], ["thyroid stimulating hormone", "tsh"]),
    "FREE_T4": ("Free T4", "ng/dL", ["nutrition"], 0, [0.01, 20], ["free t4", "ft4"]),
    "FREE_T3": ("Free T3", "pg/mL", ["nutrition"], 0, [0.1, 50], ["free t3", "ft3"]),
    "VITAMIN_D": ("Vitamin D (25-OH)", "ng/mL", ["nutrition", "musculoskeletal"], 0, [0.1, 500], ["vitamin d 25-oh", "25-oh vitamin d", "vitamin d"]),
    "VITAMIN_B12": ("Vitamin B12", "pg/mL", ["nutrition", "hematology"], 0, [1, 10000], ["vitamin b12", "b12"]),
    "FOLATE": ("Folate (vitamin B9)", "ng/mL", ["nutrition", "hematology"], 0, [0.1, 1000], ["vitamin b9 folic acid", "folate", "folic acid"]),
    "HOMOCYSTEINE": ("Homocysteine", "umol/L", ["cardiovascular", "nutrition"], -1, [0.1, 500], ["homocysteine"]),
    "TESTOSTERONE_TOTAL": ("Total testosterone", "ng/dL", ["nutrition"], 0, [0.1, 5000], ["testosterone total", "total testosterone"]),
    "CORTISOL_AM": ("Morning cortisol", "ug/dL", ["nutrition", "recovery"], 0, [0.01, 200], ["cortisol morning sample", "morning cortisol"]),
    "PSA_TOTAL": ("Total PSA", "ng/mL", ["nutrition"], 0, [0, 10000], ["prostate specific antigen total", "total psa"]),
    "TRAINING": (
        "Training volume",
        "min",
        ["functional"],
        0,
        [0, 1440],
        ["training load", "training volume"],
    ),
}
DOMAINS = [
    (
        "metabolic",
        "Metabolic health",
        "Your lipid and glucose regulation",
        "Cardiometabolic pattern",
    ),
    (
        "cardiovascular",
        "Cardiovascular",
        "Your heart and cardiorespiratory health",
        "Cardiorespiratory pattern",
    ),
    (
        "inflammatory",
        "Inflammatory profile",
        "Signals of inflammatory burden",
        "Inflammatory burden",
    ),
    (
        "recovery",
        "Recovery & resilience",
        "How well you rest and recover",
        "Reduced recovery pattern",
    ),
    (
        "musculoskeletal",
        "Muscle & strength",
        "Your strength and physical reserves",
        "Musculoskeletal pattern",
    ),
    (
        "functional",
        "Functional fitness",
        "Your capacity to move and perform",
        "Functional capacity pattern",
    ),
    (
        "body",
        "Body composition",
        "Your body composition over time",
        "Body composition pattern",
    ),
    (
        "epigenetic",
        "Molecular aging",
        "Epigenetic measures, when available",
        "Molecular aging signal",
    ),
    (
        "cognitive",
        "Cognitive context",
        "Structured cognitive measures, when available",
        "Cognitive context",
    ),
    (
        "immune",
        "Immune context",
        "Requires sufficient validated signals",
        "Immune context",
    ),
    ("hematology", "Hematology", "Your blood-cell and iron-related context", "Hematologic pattern"),
    ("liver", "Liver context", "Validated liver-associated measurements", "Liver-associated pattern"),
    ("kidney", "Kidney context", "Validated kidney and electrolyte measurements", "Kidney-associated pattern"),
    ("nutrition", "Nutritional & endocrine context", "Selected nutrient and endocrine measurements", "Nutritional / endocrine pattern"),
]
HALLMARKS = [
    {
        "id": f"h{i + 1}",
        "name": n,
        "group": "Primary" if i < 5 else "Antagonistic" if i < 8 else "Integrative",
    }
    for i, n in enumerate(
        [
            "Genomic instability",
            "Telomere attrition",
            "Epigenetic alterations",
            "Loss of proteostasis",
            "Disabled macroautophagy",
            "Deregulated nutrient sensing",
            "Mitochondrial dysfunction",
            "Cellular senescence",
            "Stem-cell exhaustion",
            "Altered intercellular communication",
            "Chronic inflammation",
            "Dysbiosis",
        ]
    )
]
EVIDENCE = [
    {
        "id": "e-hallmarks",
        "title": "Hallmarks of aging: An expanding universe",
        "year": 2023,
        "population": "Integrative review of human and experimental biology",
        "sample_size": None,
        "study_design": "Narrative review",
        "endpoint": "Framework of 12 interconnected hallmarks",
        "effect": "Biological taxonomy; not an individual diagnostic test",
        "level": "Supported",
        "citation": "https://doi.org/10.1016/j.cell.2022.11.001",
        "limitations": "Many mechanisms rely on experimental models. Routine biomarkers do not directly measure a hallmark.",
        "last_reviewed": "2026-09-15",
    },
    {
        "id": "e-activity",
        "title": "WHO guidelines on physical activity and sedentary behaviour",
        "year": 2020,
        "population": "Adults, with recommendations adapted to ability and health context",
        "sample_size": None,
        "study_design": "Evidence-based guideline",
        "endpoint": "Health, physical function and disease prevention",
        "effect": "Regular activity supports health and physical function",
        "level": "Established",
        "citation": "https://www.who.int/europe/publications/i/item/9789240014886",
        "limitations": "Population guidance, not a personalized exercise prescription or evidence of aging reversal.",
        "last_reviewed": "2026-09-15",
    },
    {
        "id": "e-diet",
        "title": "Primary prevention of cardiovascular disease with a Mediterranean diet",
        "year": 2018,
        "population": "7,447 adults at high cardiovascular risk in Spain",
        "sample_size": 7447,
        "study_design": "Randomized trial, reanalysis",
        "endpoint": "Major cardiovascular events",
        "effect": "Lower incidence of major cardiovascular events in the intervention groups",
        "level": "Supported",
        "citation": "https://doi.org/10.1056/NEJMoa1800389",
        "limitations": "Older, high-risk population; protocol departures and reanalysis; individual lipid response is not guaranteed.",
        "last_reviewed": "2026-09-15",
    },
    {
        "id": "e-sleep",
        "title": "Recommended amount of sleep for a healthy adult: a joint consensus recommendation",
        "year": 2015,
        "population": "Healthy adults aged 18–60",
        "sample_size": None,
        "study_design": "Expert consensus informed by evidence",
        "endpoint": "Sleep duration and health",
        "effect": "Regular adequate sleep supports health",
        "level": "Supported",
        "citation": "https://doi.org/10.5664/jcsm.4758",
        "limitations": "Not a trial of this protocol; consumer HRV and sleep estimates are noisy.",
        "last_reviewed": "2026-09-15",
    },
    {
        "id": "e-supplement",
        "title": "Dietary supplements for exercise and athletic performance",
        "year": 2025,
        "population": "Athletes and physically active adults; heterogeneous studies",
        "sample_size": None,
        "study_design": "NIH evidence fact sheet",
        "endpoint": "Exercise performance and safety",
        "effect": "Evidence and risks vary substantially by ingredient",
        "level": "Supported",
        "citation": "https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-HealthProfessional/",
        "limitations": "Not evidence of longevity benefit; formulation and health context matter.",
        "last_reviewed": "2026-09-15",
    },
]
RELATIONSHIPS = [
    {
        "id": "r-metabolic",
        "domain": "metabolic",
        "phenotype": "Cardiometabolic pattern",
        "process": "Altered nutrient signaling",
        "pathway": "Insulin / nutrient signaling",
        "hallmark_id": "h6",
        "level": "Hypothesis",
        "confidence": "Low",
        "evidence_ids": ["e-hallmarks"],
        "population": "Mixed human and experimental biology",
        "effect_direction": "Possible association",
        "limitations": "Lipid and glucose patterns do not identify a specific causal mechanism.",
    },
    {
        "id": "r-metabolic-inflammation",
        "domain": "metabolic",
        "phenotype": "Cardiometabolic pattern",
        "process": "Inflammatory signaling",
        "pathway": "Inflammatory communication",
        "hallmark_id": "h11",
        "level": "Hypothesis",
        "confidence": "Low",
        "evidence_ids": ["e-hallmarks"],
        "population": "Mixed human and experimental biology",
        "effect_direction": "Possible association",
        "limitations": "Nonspecific signals. This relationship is a hypothesis for an individual.",
    },
    {
        "id": "r-inflammatory",
        "domain": "inflammatory",
        "phenotype": "Inflammatory burden",
        "process": "Persistent inflammatory signaling",
        "pathway": "Inflammatory communication",
        "hallmark_id": "h11",
        "level": "Supported",
        "confidence": "Moderate",
        "evidence_ids": ["e-hallmarks"],
        "population": "Mixed human and experimental biology",
        "effect_direction": "Association",
        "limitations": "hs-CRP is nonspecific; infection, injury and other causes must be considered.",
    },
    {
        "id": "r-recovery",
        "domain": "recovery",
        "phenotype": "Reduced recovery pattern",
        "process": "Stress and inflammatory signaling",
        "pathway": "Intercellular stress response",
        "hallmark_id": "h10",
        "level": "Hypothesis",
        "confidence": "Low",
        "evidence_ids": ["e-hallmarks", "e-sleep"],
        "population": "Adult sleep studies and experimental biology",
        "effect_direction": "Possible association",
        "limitations": "Wearable trends cannot establish a molecular pathway or aging mechanism.",
    },
]
for r in RELATIONSHIPS:
    r["last_reviewed"] = "2026-09-15"
INTERVENTIONS = [
    {
        "id": "aerobic",
        "name": "Build your aerobic foundation",
        "category": "Exercise",
        "domain": "functional",
        "also": ["cardiovascular", "metabolic"],
        "level": "Established",
        "evidence_ids": ["e-activity"],
        "weeks": 12,
        "targets": ["VO2MAX", "RHR", "HRV"],
        "protocol": "Agree a gradual, tolerable aerobic plan with your care team. Record the planned sessions and intensity before starting.",
        "expected_effect": "Improved cardiorespiratory fitness; individual responses vary.",
        "risk": "Adapt to your current capacity. New chest pain, fainting or unusual breathlessness needs medical assessment.",
        "contraindications": ["unstable heart disease", "chest pain", "fainting"],
        "interactions": [],
        "burden": 0.4,
        "reversibility": "High",
        "regulatory_status": "Lifestyle option",
        "review_required": False,
    },
    {
        "id": "nutrition",
        "name": "A Mediterranean-style eating pattern",
        "category": "Nutrition",
        "domain": "metabolic",
        "also": ["cardiovascular", "body"],
        "level": "Supported",
        "evidence_ids": ["e-diet"],
        "weeks": 12,
        "targets": ["APOB", "TRIGLYCERIDES", "GLUCOSE"],
        "protocol": "Choose sustainable substitutions toward vegetables, legumes, whole grains and unsaturated fats, adapted to allergies and your dietary needs.",
        "expected_effect": "May support cardiometabolic health; measure your own response.",
        "risk": "Adapt for food allergies and medically prescribed diets. Discuss major changes if using glucose-lowering medicines.",
        "contraindications": [],
        "interactions": ["insulin", "sulfonylurea"],
        "burden": 0.3,
        "reversibility": "High",
        "regulatory_status": "Dietary pattern",
        "review_required": False,
    },
    {
        "id": "sleep",
        "name": "Create a consistent sleep window",
        "category": "Sleep",
        "domain": "recovery",
        "also": [],
        "level": "Supported",
        "evidence_ids": ["e-sleep"],
        "weeks": 4,
        "targets": ["SLEEP", "HRV", "RHR"],
        "protocol": "Set a feasible, consistent wake time and protect sufficient opportunity for sleep. Record sleep quality and any daytime symptoms.",
        "expected_effect": "More consistent sleep; recovery signals may improve.",
        "risk": "Persistent sleepiness, suspected sleep apnea or insomnia warrants clinical evaluation.",
        "contraindications": [],
        "interactions": [],
        "burden": 0.2,
        "reversibility": "High",
        "regulatory_status": "Lifestyle option",
        "review_required": False,
    },
    {
        "id": "strength",
        "name": "Build strength, sustainably",
        "category": "Exercise",
        "domain": "musculoskeletal",
        "also": ["functional", "body"],
        "level": "Established",
        "evidence_ids": ["e-activity"],
        "weeks": 12,
        "targets": ["GRIP", "MUSCLE"],
        "protocol": "Agree a progressive resistance plan appropriate to experience, mobility and injuries. Use consistent strength measurements.",
        "expected_effect": "Improved strength and physical function.",
        "risk": "Adapt load and technique to injuries and ability; use qualified guidance where needed.",
        "contraindications": ["acute injury", "chest pain"],
        "interactions": [],
        "burden": 0.4,
        "reversibility": "High",
        "regulatory_status": "Lifestyle option",
        "review_required": False,
    },
    {
        "id": "creatine",
        "name": "Creatine: a clinician-reviewed option",
        "category": "Supplement",
        "domain": "musculoskeletal",
        "also": ["functional"],
        "level": "Supported",
        "evidence_ids": ["e-supplement"],
        "weeks": 12,
        "targets": ["GRIP", "MUSCLE"],
        "protocol": "Review suitability, product quality and monitoring with a qualified professional. No automated dose recommendation.",
        "expected_effect": "May support high-intensity exercise performance; not proven to extend lifespan.",
        "risk": "Requires review of renal history, medicines, product quality and relevant labs.",
        "contraindications": ["kidney disease", "pregnancy"],
        "interactions": ["nephrotoxic"],
        "burden": 0.3,
        "reversibility": "High",
        "regulatory_status": "Dietary supplement; jurisdiction dependent",
        "review_required": True,
    },
    {
        "id": "clinical-lipids",
        "name": "Discuss persistent lipid changes with your clinician",
        "category": "Clinical care",
        "domain": "metabolic",
        "also": ["cardiovascular"],
        "level": "Supported",
        "evidence_ids": ["e-diet"],
        "weeks": 12,
        "targets": ["APOB", "LDL"],
        "protocol": "Bring longitudinal results, family history and current medicines to a qualified clinician. This card does not select or prescribe a drug.",
        "expected_effect": "Individual risk assessment and an appropriate monitoring plan.",
        "risk": "Treatment decisions and prescriptions require a qualified clinician.",
        "contraindications": [],
        "interactions": [],
        "burden": 0.2,
        "reversibility": "Clinician dependent",
        "regulatory_status": "Clinical discussion only",
        "review_required": True,
    },
]
KNOWLEDGE_ONLY = [
    {
        "id": "senolytics",
        "name": "Senolytics",
        "category": "Investigational",
        "level": "Emerging",
        "status": "Research knowledge only",
        "text": "Human evidence remains incomplete. Not offered as a self-directed experiment or ranked alongside established lifestyle options.",
        "evidence_ids": ["e-hallmarks"],
    },
    {
        "id": "mtor",
        "name": "mTOR-related gerotherapeutics",
        "category": "Investigational",
        "level": "Hypothesis",
        "status": "Research knowledge only",
        "text": "Mechanistic interest does not establish individual benefit or safety. Clinical-trial or qualified medical pathways are required.",
        "evidence_ids": ["e-hallmarks"],
    },
]
