import {
  Activity,
  Dna,
  Heart,
  Layers,
  Leaf,
  ShieldCheck,
  Sparkles,
  Zap,
  Moon,
  Dumbbell,
  Droplets,
  FlaskConical,
  TestTube2,
  Apple,
} from "lucide-react";
export const domainIcons: Record<string, any> = {
  metabolic: Leaf,
  cardiovascular: Heart,
  inflammatory: Activity,
  recovery: Moon,
  musculoskeletal: Dumbbell,
  functional: Zap,
  body: Layers,
  epigenetic: Dna,
  cognitive: Sparkles,
  immune: ShieldCheck,
  // Retained only for inspecting immutable historical Twin versions.
  hematology: Droplets,
  liver: FlaskConical,
  kidney: TestTube2,
  nutrition: Apple,
};
export const goals = [
  "Longevity",
  "General health",
  "Metabolic health",
  "Cardiovascular health",
  "Performance",
  "Body composition",
  "Recovery",
  "Cognitive health",
  "Custom",
];
